### ISSUE TITLE
Possibility to pause the downlod

### ISSUE THREAD

**Issue by Akayeshmantha** [AnthumChris/fetch-progress-indicators#15]
Hi thanks alot for the great work.Is it possible to puse the downlod ?

**Comment by anthumchris** [comment]
I think so.  [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) allows a Fetch to be stopped and `totalBytesRead` could be saved.  To resume, `totalBytesRead` could be used in an [HTTP range request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).

**Comment by Akayeshmantha** [comment]
What about writing part to the file in the users end?. Is it possible to reopen writeblestream with the same file ?

**Comment by anthumchris** [comment]
I'm not sure, I haven't tried that before.

**Comment by Akayeshmantha** [comment]
sure will give it a try and see thanks alot for the response :+1:

**Comment by anthumchris** [comment]
You're very welcome. I think adding a pause/resume feature could be nice to add as an example at some point.  I won't have time to devote to it now, unfortunately.  Reach out directly if you have any more questions. happy to help!
