### ISSUE TITLE
SSL expired

### ISSUE THREAD

**Issue by jcbhmr** [AnthumChris/fetch-progress-indicators#17]
![image](https://user-images.githubusercontent.com/61068799/217667146-f39cfc7c-8862-4137-9a42-b4cc43f629bc.png)

**Comment by anthumchris** [comment]
Thanks! TLS certs now updated: https://fetch-progress.anthum.com/

![image](https://user-images.githubusercontent.com/10064176/217978914-1d339bc2-29f6-4102-ad1c-cd9e886994fe.png)

**Comment by jcbhmr** [comment]
Awesome! 👍
